"""phase3b_team_membership_upgrade

Revision ID: 934dd7b15406
Revises: cff91e7d4be6
Create Date: 2026-09-17 20:14:07.650430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '934dd7b15406'
down_revision: Union[str, None] = 'cff91e7d4be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', 'direction', name='uq_join_request_team_user_direction')
    )
    op.create_index(op.f('ix_team_join_requests_id'), 'team_join_requests', ['id'], unique=False)
    op.create_index(op.f('ix_team_join_requests_team_id'), 'team_join_requests', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_join_requests_user_id'), 'team_join_requests', ['user_id'], unique=False)
    op.add_column('teams', sa.Column('min_members', sa.Integer(), nullable=False))
    op.add_column('teams', sa.Column('max_members', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('profile_pic', sa.String(length=500), nullable=True))
    op.add_column('teams', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'is_active')
    op.drop_column('teams', 'profile_pic')
    op.drop_column('teams', 'max_members')
    op.drop_column('teams', 'min_members')
    op.drop_index(op.f('ix_team_join_requests_user_id'), table_name='team_join_requests')
    op.drop_index(op.f('ix_team_join_requests_team_id'), table_name='team_join_requests')
    op.drop_index(op.f('ix_team_join_requests_id'), table_name='team_join_requests')
    op.drop_table('team_join_requests')
    # ### end Alembic commands ###
