"""phase3_teams_tasks

Revision ID: cff91e7d4be6
Revises: 3a483a0c4a9c
Create Date: 2026-09-10 18:14:17.194298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cff91e7d4be6'
down_revision: Union[str, None] = '3a483a0c4a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_comments_id'), 'task_comments', ['id'], unique=False)
    op.create_index(op.f('ix_task_comments_task_id'), 'task_comments', ['task_id'], unique=False)
    op.add_column('tasks', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('is_overdue', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_team_id'), 'tasks', ['team_id'], unique=False)
    op.drop_constraint('tasks_team_id_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_owner_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    op.drop_column('tasks', 'owner_id')
    op.add_column('team_members', sa.Column('member_id', sa.Integer(), nullable=False))
    op.add_column('team_members', sa.Column('role', sa.String(length=20), nullable=False))
    op.add_column('team_members', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('team_members', sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('team_members_user_id_fkey', 'team_members', type_='foreignkey')
    op.drop_constraint('team_members_team_id_fkey', 'team_members', type_='foreignkey')
    op.create_foreign_key(None, 'team_members', 'users', ['member_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'team_members', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_column('team_members', 'user_id')
    op.add_column('teams', sa.Column('join_code', sa.String(length=12), nullable=False))
    op.add_column('teams', sa.Column('visibility', sa.String(length=20), nullable=False))
    op.add_column('teams', sa.Column('leader_id', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('teams', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('teams', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_teams_join_code'), 'teams', ['join_code'], unique=True)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_foreign_key(None, 'teams', 'users', ['leader_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_join_code'), table_name='teams')
    op.alter_column('teams', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('teams', 'updated_at')
    op.drop_column('teams', 'created_at')
    op.drop_column('teams', 'leader_id')
    op.drop_column('teams', 'visibility')
    op.drop_column('teams', 'join_code')
    op.add_column('team_members', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.create_foreign_key('team_members_team_id_fkey', 'team_members', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('team_members_user_id_fkey', 'team_members', 'users', ['user_id'], ['id'])
    op.drop_column('team_members', 'joined_at')
    op.drop_column('team_members', 'status')
    op.drop_column('team_members', 'role')
    op.drop_column('team_members', 'member_id')
    op.add_column('tasks', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_owner_id_fkey', 'tasks', 'users', ['owner_id'], ['id'])
    op.create_foreign_key('tasks_team_id_fkey', 'tasks', 'teams', ['team_id'], ['id'])
    op.drop_index(op.f('ix_tasks_team_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.alter_column('tasks', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'is_overdue')
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'creator_id')
    op.drop_column('tasks', 'assignee_id')
    op.drop_column('tasks', 'note')
    op.drop_index(op.f('ix_task_comments_task_id'), table_name='task_comments')
    op.drop_index(op.f('ix_task_comments_id'), table_name='task_comments')
    op.drop_table('task_comments')
    # ### end Alembic commands ###
